# Generated by Django 3.1.6 on 2021-02-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Address2',
            new_name='address2',
        ),
    ]
